### ISSUE TITLE
[Feature Request] - Assign milestone

### ISSUE THREAD

**Issue by matthewbegun** [alex-page/github-project-automation-plus#12]
Hi, thank you so much for writing this. It's a life saver.

I use Projects to track medium term deadlines and Milestones for weekly targets; I was wondering how hard it would be to assign a milestone at the same time as the project.

I think it should be okay based on the docs and your code, but I don't really know javascript very well so I can't be sure.

Happy to have a hack if I get some spare time.

Thanks again!

**Comment by alex-page** [comment]
Hey @matthewbegun great idea!

The scope of this project is limited to projects and columns with issues and pull requests. This could easily be another action. It would be triggered on issue or pull request creation and then connect to the updateIssue to add a milestone:
https://developer.github.com/v4/input_object/updateissueinput/

**Comment by matthewbegun** [comment]
OK I'll have a poke and see if I can hack something together. 

Thanks again!
