### ISSUE TITLE
Support for delete and archive issue from project

### ISSUE THREAD

**Issue by 14113** [alex-page/github-project-automation-plus#21]
It's a great tool for automation. Thx for it!

I have one idea for improvement. 
- When we assign user on an issue, automation is going to add the issue to a specific project. This works great.
- When we unassing user from an issue, the issue is still on a specific project. It is possible to remove issue from the project?  
From source code, I don't think so :) 

Do you have plan to work on that, or even interested in PR?

**Comment by alex-page** [comment]
This is a great idea. I wonder what other options the "project card" API has that this project could use.

**Comment by UrsaDK** [comment]
This would be a fantastic addition to this project! Especially if it could support both "Remove from project" and "Archive" actions on the "project card". This would appease both: those that want to keep track of the past cards, and those that don't.

**Comment by alex-page** [comment]
I agree, thanks @UrsaDK! I have a few other projects firing off right now but I think this is the top priority for this project.

**Comment by alex-page** [comment]
This has been resolved, we may want to split archive and delete in the future.
