### ISSUE TITLE
README.md file suggested modification

### ISSUE THREAD

**Issue by affrae** [alex-page/github-project-automation-plus#33]
You may have an issue in your README.md file about workarounds for permissions issues with the standard GITHUB_TOKEN:

> ## Private repositories
> 
> In some cases you may want to do add this functionality for a private repository or one you do not have admin rights to. You may get an error like:
> ```shell
> GraphqlError: Resource not accessible by integration
> ```
> 
> When this happens you will need to:
> 1. Create a [personal access token](https://help.github.com/en/articles/creating-a-personal-access-token-for-the-command-line)
> 2. [Create a secret](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets) containing the personal access token, call it `GITHUB_TOKEN`
> 3. Change the `repo-token` in the workflow `.yml`  to reference your new token name:
> ```yaml
> repo-token: ${{ secrets.GITHUB_TOKEN }}
> ```
> 
> With certain organisations there may be SAML enforcement. This means you will need to `Enable SSO` when you create the personal access token.
> ```
> GraphqlError: Resource protected by organization SAML enforcement. You must grant your personal token access to this organization
> ```

If a user tries to create a secret called `GITHUB_TOKEN` they will be denied as it is a reserved keyword. I would suggest `MY_GITHUB_TOKEN` instead. 💜

**Comment by alex-page** [comment]
Thanks @affrae this is resolved in the latest version https://github.com/alex-page/github-project-automation-plus/releases/tag/v0.2.3
