### ISSUE TITLE
Add a troubleshooting guide

### ISSUE THREAD

**Issue by pandafy** [alex-page/github-project-automation-plus#38]
Add which permissions are needed to be selected while creating personal access token.

**Comment by alex-page** [comment]
Hey @pandafy great idea. Did you want to contribute some documentation in the README.md?

**Comment by pandafy** [comment]
I would love to but I don't have any idea which permissions are needed to be selected. 
We can add troubleshooting guides for :
- Bad credentials
- Can't read repository null (I didn't gave access to privare repository, but it solved after giving this access)
- Access to public repository is must to maintain project board.

**Comment by alex-page** [comment]
I think these are the scenarios I know of. Will have to figure out the exact different permissions for each. I put some guesses for permissions.

**repo** Full control of private repositories
- Public repository and project board
- Private repository and project board

**admin:org** Full control of orgs and teams, read and write org projects
- Organisation project board
- Organisation public repository with project board
- Organisation private project board
- Organisation with private repository and project board

**?** Not sure on this one
- User account has a project board
- User account has a private project board

**Comment by pandafy** [comment]
> **repo** Full control of private repositories
> 
> * Public repository and project board
> * Private repository and project board

I didn't need to give full control of private repositories for a public repository I used this with. We should encourage users to follow concept of `Least Privilege Permissions`.

**Comment by alex-page** [comment]
Definitely agree on least permissions. I think for next steps we need to do a manual test with each scenario and minimal permissions to make sure they are correct. 

I'm happy to do it but I have some other priorities this week.

**Comment by alex-page** [comment]
Another error state was found by @canarro https://github.com/alex-page/github-project-automation-plus/issues/39#issuecomment-629562241

**Comment by pandafy** [comment]
II will try to do manual testing of required permissions over the weekend. :smile:

**Comment by pandafy** [comment]
There is one more thing which should be added in the documentation, `Contributing Guidelines`.  @alex-page I don't think you ever expected people to contribute to your work. 😆

**Comment by rodrigondec** [comment]
@alex-page 

It will be good to document this too: https://github.com/actions/toolkit/issues/465#issuecomment-630227277.
>from #39

**Comment by alex-page** [comment]
I feel like I should handle an error if the secret is an empty string? What do you think @rodrigondec ?

**Comment by rodrigondec** [comment]
> I feel like I should handle an error if the secret is an empty string? What do you think @rodrigondec ?

I think it is the best case. And add to the docs about this limitation (of the github itself) with references.

**Comment by alex-page** [comment]
Yeah i will re-open #39 and we can resolve it with this guide. That would be great @rodrigondec.

**Comment by pandafy** [comment]
Apologies @alex-page , I have been busy lately. Please go ahead to create a PR. I will try to give my inputs along the way. :sweat_smile:
