### ISSUE TITLE
[BUG] ##[error]Parameter token or opts.auth is required

### ISSUE THREAD

**Issue by rodrigondec** [alex-page/github-project-automation-plus#39]
# Resume
I'm receiving the error `##[error]Parameter token or opts.auth is required` on [this run](https://github.com/idvogados/idvogados.github.io/pull/16/checks?check_run_id=668944788) on my CI

## Proofs
![image](https://user-images.githubusercontent.com/3301060/81755574-858bfe80-948f-11ea-831b-3de3218eec20.png)
![image](https://user-images.githubusercontent.com/3301060/81755592-92105700-948f-11ea-909b-5b0af074a577.png)

# Description & code digging
> I found this issue actions/toolkit#324 by googling the error returned.

On [this line of code of this action](https://github.com/alex-page/github-project-automation-plus/blob/b4737e8091f494be6ec5afdb07dc388a13e5bd6d/src/index.js#L18) is used:

```js
const octokit = new github.GitHub(token);
```

In the package `@actions/github` on [this line of code](https://github.com/actions/toolkit/blob/0471ed4ad777277385d971c0c86c87917e9373df/packages/github/src/github.ts#L39) (which probably raises the error) is used:
```js
constructor(token: string, opts?: Omit<Octokit.Options, 'auth'>)
  constructor(opts: Octokit.Options)
  constructor(token: string | Octokit.Options, opts?: Octokit.Options) {
    super(GitHub.getOctokitOptions(GitHub.disambiguate(token, opts)))

    this.graphql = GitHub.getGraphQL(GitHub.disambiguate(token, opts))
  }
```
> Github extends Ocktokit. So is super = Ocktokit

In the package `@ocktokit/core` on [this line of code](https://github.com/octokit/core.js/blob/f099459fd01be79187275ddf47d77a2797188c6a/src/index.ts#L132) there's the following explanation/documentation:
```js
constructor(options: OctokitOptions = {}) {
[...]

// (1) If neither `options.authStrategy` nor `options.auth` are set, the `octokit` instance
    //     is unauthenticated. The `this.auth()` method is a no-op and no request hook is registred.
    // (2) If only `options.auth` is set, use the default token authentication strategy.
    // (3) If `options.authStrategy` is set then use it and pass in `options.auth`. Always pass own request as many strategies accept a custom request instance.
    // TODO: type `options.auth` based on `options.authStrategy`.
```

# Questions
Should be passed others args besides the token on this line from the action?
```js
const octokit = new github.GitHub(token);
```

The construct does accept other options:
```js
constructor(token: string, opts?: Omit<Octokit.Options, 'auth'>)
```

On the [official documentation of `@actions/github`](https://github.com/actions/toolkit/tree/master/packages/github#usage) is used only `token` on the constructor.

Did we miss some official documentation? Should issues be opened on [`@actions/github`]( https://github.com/actions/toolkit/tree/master/packages/github) and [`@ocktokit/core`](https://github.com/octokit/core.js)?

**Comment by alex-page** [comment]
Hey @rodrigondec thanks so much for raising this issue and providing all the detailed information. 

Do you know how to fix it? I will have to spend some time investigating the problem.

**Comment by rodrigondec** [comment]
Don't know either. 

I have re-run the job but still has error. I'm using your action on other projects and didn't have this issue.

I don't understand either why did it happen by analyzing the code and ref I found.

**Comment by conarro** [comment]
I just ran into this error as well. I had stored the `GH_TOKEN` at the org-level initially. When I moved it to a repo-level secret, the action worked!

**Comment by alex-page** [comment]
Oh that is interesting! I will add it to issue #38 thanks @conarro!

**Comment by pandafy** [comment]
> I just ran into this error as well. I had stored the `GH_TOKEN` at the org-level initially. When I moved it to a repo-level secret, the action worked!

If I get you correct, you have a project in a repository which is part of an organization. Shouldn't organization level access also provide access to projects of all repositories ?

**Comment by pandafy** [comment]
I think it is a tedious job to configure secret for all repositories of an organization. @alex-page is this intentionally or there is not a straight forward way to allow organization level token manage projects of all repositories. 

On a personal note, I won't like configuring secrets for all repositories individually.

**Comment by alex-page** [comment]
Yeah it is definitely hard. I would avoid documenting organization secrets or have a sentence saying we don't recommend it's usage.

This is also confusing if people set up private repos in organisations:
> Organization secrets cannot be used by private repositories with your plan.
> Please consider upgrading your plan if you require this functionality.

**Comment by rodrigondec** [comment]
> 
> 
> I just ran into this error as well. I had stored the `GH_TOKEN` at the org-level initially. When I moved it to a repo-level secret, the action worked!

I have my secrets on the repo itself. Not on the org.

This bug is highly esoteric 🤣 

# Proofs
![image](https://user-images.githubusercontent.com/3301060/82132955-234b3a80-97bc-11ea-9c15-42a733e92e82.png)
![image](https://user-images.githubusercontent.com/3301060/82132963-31995680-97bc-11ea-8d50-daab489ecd03.png)

**Comment by rodrigondec** [comment]
@alex-page digged some other codes. I edited the issue 😄

**Comment by alex-page** [comment]
@rodrigondec some people had issues using `GH_TOKEN` can you try renaming your secret to `GITHUB_TOKEN`?

**Comment by rodrigondec** [comment]
> 
> 
> @rodrigondec some people had issues using `GH_TOKEN` and `GITHUB_TOKEN` can you try renaming your secret to something else? #33

Sure, I'll modify and post the results.

**Comment by rodrigondec** [comment]
@alex-page 

I switched the name of my secret and put it on the Organization.

The [run I tested](https://github.com/idvogados/idvogados.github.io/runs/683276332?check_suite_focus=true) worked perfectly fine.


## Proofs
![image](https://user-images.githubusercontent.com/3301060/82158172-94dac580-985c-11ea-8fb0-9ad18b485f15.png)

![image](https://user-images.githubusercontent.com/3301060/82158196-c6539100-985c-11ea-813a-d2f1fb8f1119.png)

**Comment by alex-page** [comment]
@rodrigondec that might be a good idea. I have secrets in organisation repositories and it works for me fine. I wonder if there is something else going on here?

**Comment by conarro** [comment]
> @rodrigondec some people had issues using `GH_TOKEN` and `GITHUB_TOKEN` can you try renaming your secret to something else? #33

I tried using `GH_ACCESS_TOKEN` the org-level, still didn't work. It's working for me with repo-level secrets called `GH_TOKEN`.

Will post back here if I do any other combinations.


> I have secrets in organisation repositories

Just to clarify, the issue here is not having secrets in organization _repositories_, but secrets that live at the organization-level itself.

**Comment by rodrigondec** [comment]
> > @rodrigondec some people had issues using `GH_TOKEN` and `GITHUB_TOKEN` can you try renaming your secret to something else? #33
> 
> I tried using `GH_ACCESS_TOKEN` the org-level, still didn't work. It's working for me with repo-level secrets called `GH_TOKEN`.
> 
> Will post back here if I do any other combinations.
> 
> > I have secrets in organisation repositories
> 
> Just to clarify, the issue here is not having secrets in organization _repositories_, but secrets that live at the organization-level itself.

@conarro is it running from forked repos? I opened a issue on actions/toolkit#465 and discovered the cause for my error.

https://github.com/alex-page/github-project-automation-plus/issues/38#issuecomment-630318533

**Comment by alex-page** [comment]
Re-opening this issue until  #38 is done

**Comment by conarro** [comment]
> is it running from forked repos?

@rodrigondec no, no forks in my setup sadly.
