### ISSUE TITLE
Update documentation for forked pull requests

### ISSUE THREAD

**Issue by alex-page** [alex-page/github-project-automation-plus#49]
GitHub has made it possible to run actions on forked prs

https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/

Docs need to say that the user can now enable a setting to run actions on the forked repo.

**Comment by NicholasBoll** [comment]
Also, update the allowed events to include `pull_request_target`: https://github.com/NicholasBoll/test-github-actions/runs/955762031?check_suite_focus=true
