### ISSUE TITLE
(README.md) Personal access tokens for public user projects

### ISSUE THREAD

**Issue by j1elo** [alex-page/github-project-automation-plus#51]
The README says that for

> Private repository and project board

the required permission is `repo` ("*Full control of private repositories*").

However, this permission is actually required also for **public** repositories and project boards.

I've tested it with a public user-level Project: https://github.com/users/j1elo/projects/1
and a public repository: https://github.com/j1elo/test-repo

* Using `secrets.GITHUB_TOKEN` fails with error `Resource not accessible by integration` (e.g. https://github.com/j1elo/test-repo/actions/runs/274046708)
* Using `write:org` ("*Read and write org and team membership, read and write org projects*") causes an empty GraphQL response and the error `Could not find the column "..." or project "..."` (e.g. https://github.com/j1elo/test-repo/actions/runs/274113617) -- I tried this one just to test if user-level Projects had the same permissions as Organization Projects
* At this point, I tried using all of the `repo` sub-scopes (`repo:status`, `repo_deployment`, `public_repo`, `repo:invite`, `security_events`), and it also causes an empty query response.
* Finally, using the whole `repo` allowed the query to find the requested Project.

**Proposed fix:**

Either the README should be updated to reflect that `repo` is needed also for public user Projects and public repos; or else, if possible at all, the query should be made in a way that doesn't require full `repo` permissions just to search for existing Projects.

In any case, thank you very much for this action! :-)

**Comment by alex-page** [comment]
Hey @j1elo thanks for the detailed issue! Do you want to make a PR to update it. Would be happy to make this change.

**Comment by j1elo** [comment]
I wouldn't have enough knowledge about how to work with the GraphQL queries and Github permissions to know how to avoid that the `repo` permissions are needed (ideally, the less permissions the better); or to know if it is even possible to avoid having that permission (is it?)

Otherwise, yes I can propose a change to the README.

**Comment by D4nte** [comment]
So is the proper solution to have a token with whole `repo` permission?

**Comment by alex-page** [comment]
@D4nte yes so it can access issues and pull requests. Are you having issues with this?

**Comment by D4nte** [comment]
Now fixed. Thanks!

**Comment by alex-page** [comment]
@j1elo I have updated the documentation. Closing this issue for now but please re-open it if anything is missing.
