### ISSUE TITLE
How does this work with an organization owned project?

### ISSUE THREAD

**Issue by affrae** [alex-page/github-project-automation-plus#54]
Hi!

Can you clarify how this action would work with an organization-owned project?

Let's say Organization OrgA owns Repository RepoB - which has the workflow.yml  file installed - and Project ProjC

I want to trigger the workflow such that when someone opens an issue in RepoB, the workflow will add to a particular column (let's say "Triage") in ProjC.

Will this action work in that context?

**Comment by alex-page** [comment]
Not right now, it's only focused on supporting one project.

**Comment by carlisia** [comment]
Hey all, I made this work. 

1. Create ProjC in a GH organization
2. Add a GH secret at the org level, NOT named `GITHUB_SECRET`; name it something like `GH_SECRET`
3. Give full `repo` access for this secret; copy/paste somewhere the value of this created secret
4. Add the yaml configuration to repo RepoB pointing to project:ProjC, and with the secret name created above
5. In the repo RepoB, go to Settings and add a secret pair, name it `GH_SECRET` and add the value generated for the secret created above.

Start adding issues.

This works with multiple repos too, just do steps 4 and 5 for whichever repo you want to have its new issues displayed in the org level project.

**Comment by yuvipanda** [comment]
Thank you for writing this up, @carlisia!

Can you tell me what step (3) entails? Create a github personal access token with full 'repo' access? Or something else? That would be very helpful!

**Comment by carlisia** [comment]
Sure thing!

> Create a github personal access token with full 'repo' access?

Yes.

**Comment by alex-page** [comment]
Thank you so much @carlisia. I am going to close this for now and hopefully folks can reference this issue. If it gets raised often I can add these steps to the `README.md` file.

**Comment by fharper** [comment]
The steps mentioned by @carlisia didn't work for me, but here's what worked:

1. Create a personal token that have access to the `write:org` + anything else you want the action to have access, specially in `repo:*`;
2. Create a secret at the repository level with the value from the personal token you created;
3. Use that secret name in the action configuration.

Repeat the last two steps for all repos.
