### ISSUE TITLE
[Feature] Automatically moves the Issue/PR based on the label selected for it

### ISSUE THREAD

**Issue by hussain5416** [alex-page/github-project-automation-plus#60]
Just for an example: Let's say there are 3 projects I made in a repo called `All Bugs`, `All improvements`, `All feature requests`. And lets say 3 labels `bug`, `improve`, `feature`. If issue was labeled as bug, issue/pr moves to `All Bugs` project and so on for others.

Another example, like you can have **projects based on the components of the app** you are working on, and just by labelling it, it would automatically show in that app-component related project.

**Possibilities are unlimited,** 

I hope you consider it.

**Comment by hussain5416** [comment]
@alex-page Any comment on this one?

**Comment by alex-page** [comment]
You should be able to do this with three actions. Is the suggestion to do multiple with the one action?

**Comment by hussain5416** [comment]
@alex-page "You should be able to do this with three actions." Can you elaborate on this one.

**Comment by alex-page** [comment]
You could create three [workflow files](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions) for the github repos you want to collocate the issues or pull requests in.

Each workflow could do something like:
- On PR/Issue getting label `bug` move PR/Issue to backlog column of `All Bugs` project
- On PR/Issue getting label `improve` move PR/Issue to backlog column of `All Imrpovements` project
- On PR/Issue getting label `feature` move PR/Issue to backlog column of `All Features` project
