### ISSUE TITLE
Automate README.md version number from package.json so it doesn't get out of date

### ISSUE THREAD

**Issue by alex-page** [alex-page/github-project-automation-plus#7]
It makes sense for guidance to say the current latest version to make sure that master doesn't accidentally break consumers.

I will forget to update this version number in the documentation. I should work out a way to automate the number increment in the `README.md`.

**Comment by AndrewMusgrave** [comment]
I'm going to create a script to update mine this weekend so it'll let you know when I do 😄

**Comment by alex-page** [comment]
My first thoughts were `MDX` but it could probably be a very small script. Good idea!
