### ISSUE TITLE
Periodically move issue from one status to another

### ISSUE THREAD

**Issue by kerrychu** [alex-page/github-project-automation-plus#86]
hey @alex-page 

Great initiative! 

Our team's workflow is todo -> in progress -> review -> completed

those are the status of our issues.

**User story: 
as a developer, I would like to see our issues in complete columns only reflect those completed in the past day.**

So it would be nice to have a feature to allow users to periodically move the issue from completed to maybe a different status (for example, closed or past-completion) so that the complete column in the user's project board would not be cluttered with all past completed issues.

Are you aware if there's a way to do it? if not, here is a friendly feature request 😛

**Comment by alex-page** [comment]
I think you could set up a GitHub action to run a cron job with this action to move issues. I don't have the time right now to write up an example but all the puzzle pieces should be there. Going to close this issue, if there is anything blocking please do re-open it.
