### ISSUE TITLE
Update node16 to node20

### ISSUE THREAD

**Issue by lkostrowski** [alex-page/github-project-automation-plus#90]
Node 16 is depreacted and Github will bump runtimes eventually

**Comment by alex-page** [comment]
If you want to do a PR to increase it to node 18 I would be happy to ship that. I wouldn't want to jump to 20 too soon.

**Comment by lkostrowski** [comment]
Hmm, not sure if node18 is supported 🤔 

https://github.com/actions/runner/blob/main/src/Runner.Common/Util/NodeUtil.cs#L9

**Comment by alex-page** [comment]
TIL if you want to change this number to 20 please do: https://github.com/dhruvkb/github-project-automation-plus/blob/f1ec7354e5be4f3e61eb052ca3caf4b7ce62c29a/action.yml#L21

**Comment by lkostrowski** [comment]
Not sure why you mentioned fork, anyway:

https://github.com/alex-page/github-project-automation-plus/pull/91
